spring:
  datasource:
    hikari:
      connection-test-query: SELECT 1 FROM DUAL
      connectionTimeout: 90000
      maximum-pool-size: 50
      minimum-idle: 2
      max-lifetime: 30000
    url: ${PRODUCT_DATASOURCE_URL:jdbc:oracle:thin:@localhost:1521:XE}
    username: ${PRODUCT_DATASOURCE_USERNAME:system}
    password: ${PRODUCT_DATASOURCE_PASSWORD:1978}
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
server:
  port: 8081
